name: HACS Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate HACS
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: HACS Action
        uses: hacs/action@dcb30e72781db3f207d5236b861172774ab0b485 # main
        with:
          category: integration
